
export const KEY_LIGHT_CONTROLS_1 = 'LIGHT_CONTROLS_1'
export const KEY_LIGHT_CONTROLS_2 = 'LIGHT_CONTROLS_2'
export const KEY_PLANET_EARTH_MAP = 'PLANET_EARTH_MAP'
export const KEY_PLANET_EARTH_BUMP = 'PLANET_EARTH_BUMP'
export const KEY_PLANET_EARTH_SPEC = 'PLANET_EARTH_SPEC'
export const KEY_PLANET_EARTH_CLOUD_MAP = 'PLANET_EARTH_CLOUD_MAP'
export const KEY_PLANET_EARTH_CLOUD_MAP_TRANS = 'PLANET_EARTH_CLOUD_MAP_TRANS'
