# before start project please create file "api.config.yml" and paste this configuration
db:
  mongo:
    host: localhost
    port: 27017
    dbName: null
server:
  host: localhost
  port: 3000
accessControl:
  - http://localhost:8080
socket:
  host: 127.0.0.1
  port: 3333
mail:
  sender: Game Iron War Online
  transporter:
    host: smtp.gmail.com
    port: 465
    secure: false # true for 465, false for other ports
    auth:
      user: game.iron.war@gmail.com  # generated ethereal user
      pass: account.pass  # generated ethereal password